name: Build


on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Examine input
        run: tree

      - name: Run CMake
        run: cmake CMakeLists.txt

      - name: Examine output
        run: tree
