name: Build


on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Examine input
        run: tree

      - name: Generate CMake buildsystem
        run: cmake -B out

      - name: Examine CMake output
        run: tree
