name: Build


on: push


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Examine input
        run: tree

      - name: Run CMake
        run: cmake CMakeLists.txt

      - name: Examine CMake output
        run: tree

      - name: Run make
        run: make

      - name: Examine make output
        run: tree